#' Extract Station Coordinates Robustly
#'
#' Retrieves the metadata for a given station using the URL generated by
#' \code{smndata_get_url}, searches for lines containing "Latitud", "Longitud", and "Altitud"
#' (case-insensitive), and extracts the first numeric value found in each line. If any coordinate
#' cannot be extracted or if the metadata is insufficient, NA is returned for that coordinate.
#'
#' @param station Station code (character or numeric).
#' @return A data frame with one row and the following columns:
#'   \describe{
#'     \item{latitude}{Station latitude (numeric).}
#'     \item{longitude}{Station longitude (numeric).}
#'     \item{altitude}{Station altitude (numeric).}
#'   }
#'
#' @examples
#' \dontrun{
#'   # Attempt to extract coordinates for station 28264.
#'   coords <- smndata_extract_coordinates(28264)
#'   print(coords)
#' }
#'
#' @export
smndata_extract_coordinates <- function(station) {
  station <- as.character(station)
  url <- smndata_get_url(station)

  # Read all lines from the metadata file
  lines <- tryCatch({
    readLines(url)
  }, error = function(e) {
    warning("Error reading metadata for station ", station, ": ", conditionMessage(e))
    return(NULL)
  })

  if (is.null(lines) || length(lines) < 1) {
    warning("Insufficient metadata for station ", station)
    return(data.frame(latitude = NA, longitude = NA, altitude = NA))
  }

  # Search for lines containing coordinate keywords (case-insensitive)
  lat_line_index <- grep("Latitud", lines, ignore.case = TRUE)
  lon_line_index <- grep("Longitud", lines, ignore.case = TRUE)
  alt_line_index <- grep("Altitud", lines, ignore.case = TRUE)

  if (length(lat_line_index) < 1 || length(lon_line_index) < 1 || length(alt_line_index) < 1) {
    warning("Metadata for station ", station, " does not contain complete coordinate information.")
    return(data.frame(latitude = NA, longitude = NA, altitude = NA))
  }

  # Take the first matching line for each coordinate
  lat_line <- lines[lat_line_index[1]]
  lon_line <- lines[lon_line_index[1]]
  alt_line <- lines[alt_line_index[1]]

  # Helper function to extract the first numeric value from a text string
  extract_numeric <- function(line) {
    num <- regmatches(line, regexpr("[-+]?[0-9]*\\.?[0-9]+", line))
    as.numeric(num)
  }

  latitude  <- extract_numeric(lat_line)
  longitude <- extract_numeric(lon_line)
  altitude  <- extract_numeric(alt_line)

  if (is.na(latitude) || is.na(longitude) || is.na(altitude)) {
    warning("Could not properly extract coordinates for station ", station)
  }

  return(data.frame(latitude = latitude, longitude = longitude, altitude = altitude))
}
