#' Extract Station Coordinates
#'
#' Reads the metadata file for a given station (using the URL generated by
#' \code{smndata_get_url}) and extracts the latitude, longitude, and altitude.
#'
#' This function mimics the behavior of the original \code{extraer_coordenadas}
#' by reading 9 rows of metadata (skipping the first 9 lines) and then extracting
#' the numeric values from row 7 (latitude), row 8 (longitude), and row 9 (altitude)
#' in the second column.
#'
#' @param station Station code (character or numeric).
#' @return A data frame with one row and the following columns:
#' \describe{
#'   \item{station}{Station code.}
#'   \item{latitude}{Station latitude (numeric).}
#'   \item{longitude}{Station longitude (numeric).}
#'   \item{altitude}{Station altitude (numeric).}
#' }
#' @examples
#' \dontrun{
#'   # Extract coordinates for station "15101"
#'   coords <- smndata_extract_coordinates("15101")
#'   print(coords)
#' }
#' @export
smndata_extract_coordinates <- function(station) {
  # Get the URL for the station metadata
  url <- smndata_get_url(station)

  # Read 9 lines of metadata (skip the first 9 lines)
  meta_df <- tryCatch({
    utils::read.table(file = url,
                      sep = ":",
                      header = FALSE,
                      nrows = 9,
                      skip = 9,
                      stringsAsFactors = FALSE)
  }, error = function(e) {
    stop("Error reading metadata for station ", station, ": ", conditionMessage(e))
  })

  # Ensure there are enough rows
  if (nrow(meta_df) < 9) {
    stop("Not enough metadata lines to extract coordinates for station ", station)
  }

  # Extract latitude, longitude, and altitude using the helper function
  latitude  <- smndata_extract_numeric(meta_df$V2[7])
  longitude <- smndata_extract_numeric(meta_df$V2[8])
  altitude  <- smndata_extract_numeric(meta_df$V2[9])

  if (is.na(latitude) || is.na(longitude) || is.na(altitude)) {
    warning("Could not properly extract coordinates for station ", station)
  }

  data.frame(
    station = station,
    latitude = latitude,
    longitude = longitude,
    altitude = altitude,
    stringsAsFactors = FALSE
  )
}
