#' Download Raw Daily Data for a Station
#'
#' Downloads and returns the raw daily data for a given station using the URL generated by
#' \code{smndata_get_url}. This function employs \code{readr::read_table2} for efficient data reading
#' and defines the appropriate column types. In case of an error during download or reading, the function
#' stops with a descriptive error message.
#'
#' @param station Station code (character or numeric).
#' @return A data frame with the following columns:
#' \describe{
#'   \item{date}{Date of the record.}
#'   \item{prec}{Precipitation.}
#'   \item{evap}{Evaporation.}
#'   \item{tmax}{Maximum temperature.}
#'   \item{tmin}{Minimum temperature.}
#' }
#'
#' @examples
#' \dontrun{
#'   # Example: Download raw data for station "15101"
#'   df_raw <- smndata_download_station_raw("15101")
#'   head(df_raw)
#' }
#'
#' @export
smndata_download_station_raw <- function(station) {
  # Generate the download URL for the station
  url <- smndata_get_url(station)

  # Download and read the data using readr::read_table2
  df <- tryCatch({
    readr::read_table2(
      url,
      col_names = c("date", "prec", "evap", "tmax", "tmin"),
      col_types = readr::cols(
        date = readr::col_date(format = ""),
        prec  = readr::col_double(),
        evap  = readr::col_double(),
        tmax  = readr::col_double(),
        tmin  = readr::col_double()
      ),
      skip = 25,
      na = "NULO"
    )
  }, error = function(e) {
    stop("Error downloading or reading data for station ", station, ": ", conditionMessage(e))
  })

  return(df)
}
